export const lang = {
  english: {
    search: "Search",
    gptSearchPlaceholder: "What would you like to watch today?",
    suggestions: "Suggestions",
    play: "Play",
    moreInfo: "More Info",
    nowPlaying: "Now Playing",
    popular: "Popular",
    topRated: "Top Rated",
    upcoming: "Upcoming",
    about: "About",
    signOut: "Sign Out",
  },
  hindi: {
    search: "खोजे",
    gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
    suggestions: "सुझाव",
    play: "शुरू करे",
    moreInfo: "और जानकारी",
    nowPlaying: "अब चल रहा है",
    popular: "लोकप्रिय",
    topRated: "टॉप रेटेड",
    upcoming: "आगामी",
    about: "के बारे में",
    signOut: "बहार जाये",
  },
  spanish: {
    search: "Buscar",
    gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
    suggestions: "Sugerencias",
    play: "Comenzar",
    moreInfo: "Más información",
    nowPlaying: "Ahora corriendo",
    popular: "Popular",
    topRated: "Los más valorados",
    upcoming: "Próxima",
    about: "Acerca de",
    signOut: "Desconectar",
  },
}
